flags: {}
packages:
- location: './'
- location:
    git: https://github.com/leftaroundabout/manifolds.git
    commit: master
- location:
    git: https://github.com/leftaroundabout/constrained-categories.git
    commit: master
- location:
    git: https://github.com/leftaroundabout/free-vector-spaces.git
    commit: master
extra-deps:
- manifolds-core-0.4.3.0
- vector-space-0.11
resolver: lts-8.0
